app:
  name: "web_app"
  mode: "dev"
  port: 8080

log:
  level: "debug"
  filename: "web_app.log"
  max_size: 200
  max_age: 30
  max_backups: 7
mysql:
  host: "127.0.0.1"
  port: 3306
  user: "root"
  password: "123456"
  dbname: "test"
redis:
  host: "127.0.0.1"
  port: 6379
  password: ""
  pool_size: 100
  db: 0